### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by strivedi02** [MycroftAI/mycroft-precise#107]
```
engine = PreciseEngine('.venv/bin/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
runner.start()
```
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Projects/wakeup_word_testing/mycroft_precise/mycroft-core/mycroft-precise/runner/precise_runner/runner.py", line 240, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/Projects/wakeup_word_testing/mycroft_precise/mycroft-core/mycroft-precise/runner/precise_runner/runner.py", line 67, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float:
```
I have tried all the different versions of TensorFlow, but with all the different versions getting the same error every time.
OS: Ubuntu 18.04 x86_64

**Comment by forslund** [comment]
That sounds a bit like there is some sort of error message that mycroft tries to interpret as a float. Can you see if using the precise-engine directly with your model and a wav results in a correct output:

`~/.mycroft/precise/precise-engine/precise-engine path/to/model.pb < path/to/example.wav`

What I tried as reference:

` ~/.mycroft/precise/precise-engine/precise-engine .mycroft/precise/hey-mycroft.pb < hey_mycroft.wav`

If that works it may be a mycroft-core configuration issue.

**Comment by strivedi02** [comment]
```
~/.mycroft/precise/precise-engine/precise-engine ~/.mycroft/precise/hey-mycroft.pb < ~/Desktop/hey_mycroft.wav
```
Output: 5.8175556e-06
I ran the command and yes I got the output.
So what should I do next?
Maybe I think I am still unclear about the Mycroft-precise setup part with the Mycroft-core.

On more research, I figured out that in runner.py at line 130
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Shubham/Projects/wakeup_word_testing/mycroft_precise/mycroft-core/mycroft-precise/runner/precise_runner/runner.py", line 242, in _handle_predictions
    if self.detector.update(prob):
  File "/Shubham/Projects/wakeup_word_testing/mycroft_precise/mycroft-core/mycroft-precise/runner/precise_runner/runner.py", line 130, in update
    chunk_activated = float(prob) > 1.0 - self.sensitivity
ValueError: could not convert string to float:
```
This is line is the reason

**Comment by forslund** [comment]
That error is usually if a non-number response is received by precise-runner from precise engine. this is usually an error message. (such as model file is missing or model couldn't be loaded)

I was under impression you were using a model you had created yourself?

If the model works when used with the precise executable it's likely a mycroft configuration error.

**Comment by strivedi02** [comment]
That helped me!
```
engine = PreciseEngine('.venv/bin/precise-engine', '/home/.mycroft/precise/hey-mycroft.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
runner.start()
```
Output: hello
Thanks @forslund for your help
