### ISSUE TITLE
Raspberry Pi4 Buster precise-listen python 3.7 'typing' AttributeError

### ISSUE THREAD

**Issue by varungujjar** [MycroftAI/mycroft-precise#130]
Although 'precise-listen' and 'precise-collect' works on pytthon 3.6.x having trouble running it on python 3.7  heres the error..  seems theres something not right with typing package of python also was able to install the requirements.txt.   

What have I tried after doing a little google:
uninstall typing 3.6.6 and install 3.7 for python 3.7

still no luck :(

Traceback (most recent call last):
  File "/home/pi/env/bin/precise-listen", line 11, in <module>
    load_entry_point('mycroft-precise==0.3.0', 'console_scripts', 'precise-listen')()
  File "/home/pi/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/pi/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/pi/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/env/lib/python3.7/site-packages/mycroft_precise-0.3.0-py3.7.egg/precise/scripts/listen.py", line 24, in <module>
    from precise.network_runner import Listener
  File "/home/pi/env/lib/python3.7/site-packages/mycroft_precise-0.3.0-py3.7.egg/precise/network_runner.py", line 18, in <module>
    from typing import *
  File "/home/pi/env/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/pi/env/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

**Comment by varungujjar** [comment]
ok so i upgraded my tensorflow from 1.13  -->  1.14  and also upgraded my keras ->2.3.1 and now it works fine.
