### ISSUE TITLE
Can't use compiled engine from dev branch 

### ISSUE THREAD

**Issue by Tony763** [MycroftAI/mycroft-precise#152]
Hi, I'am having trouble getting working engine from dev branch 3.0.0.

Steps tu build and install:
```
cd /srv/mycroft-precise
rm -r .venv
rm -r build
rm -r dist

bash setup.sh
bash build.sh

rm -r /home/tony/.mycroft/precise/precise-engin*
sudo rm -r /var/www/html/precise-engin*
sudo cp -r /srv/mycroft-precise/dist/precise-engin* /var/www/html/
mycroft-pip install /srv/mycroft-precise/runner

mycroft-config edit user
###
{
  "max_allowed_core_version": 20.2,
  "lang": "cs-cz",
  "listener": {
    "wake_word": "subaru",
    "stand_up_word":"wake up"
  },
  "hotwords": {
    "subaru": {
      "module": "precise",
      "local_model_file": "/srv/mycroft-precise/subaru.pb",
      "sensitivity": 0.5,
      "trigger_level":2
    },
    "wake up":{
      "module":"pocketsphinx",
      "phonemes":"W EY K . AH P",
      "threshold":1e-20,
      "lang":"en-us"
    }
  },
  "tts": {
    "module": "espeak",
    "espeak": {
      "lang": "cs",
      "voice": "m1"
    }
  },
  "precise": {
    "dist_url": "http://10.0.1.1/precise-engine_0.3.0_x86_64.tar.gz",
    "model_url": "https://raw.githubusercontent.com/MycroftAI/precise-data/models-dev/{wake_word}.tar.gz"
  }
}
###
mycroft-start debug
```

Mycroft output:
```
 12:43:40.269 | INFO     | 31996 | mycroft.client.speech.hotword_factory:on_complete:257 | Precise download complete!
12:43:40.478 | INFO     | 31996 | mycroft.client.speech.hotword_factory:load_module:386 | Loading "subaru" wake word via pocketsphinx
 12:43:40.500 | INFO     | 31996 | mycroft.client.speech.listener:create_wakeup_recognizer:360 | creating stand up word engine
 12:43:40.501 | INFO     | 31996 | mycroft.client.speech.hotword_factory:load_module:386 | Loading "wake up" wake word via pocketsphinx

 12:43:41.483 | INFO     | 31996 | mycroft.client.speech.listener:create_wake_word_recognizer:323 | Creating wake word engine
 12:43:41.484 | INFO     | 31996 | mycroft.client.speech.listener:create_wake_word_recognizer:346 | Using hotword entry for subaru
 12:43:41.485 | WARNING  | 31996 | mycroft.client.speech.listener:create_wake_word_recognizer:348 | Phonemes are missing falling back to listeners configuration
 12:43:41.486 | WARNING  | 31996 | mycroft.client.speech.listener:create_wake_word_recognizer:352 | Threshold is missing falling back to listeners configuration
 12:43:41.486 | INFO     | 31996 | mycroft.client.speech.hotword_factory:load_module:386 | Loading "subaru" wake word via precise

 12:43:41.763 | INFO     | 31996 | mycroft.client.speech.listener:create_wakeup_recognizer:360 | creating stand up word engine
 12:43:41.764 | INFO     | 31996 | mycroft.client.speech.hotword_factory:load_module:386 | Loading "wake up" wake word via pocketsphinx

[32285] Failed to execute script pyi_rth_pkgres
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/srv/mycroft-precise/.venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "pkg_resources/__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'





```

**Comment by Tony763** [comment]
Problem is with pip packages:
PyInstaller==3.6  
Setuptools
NumPy==1.16.0

Related issues:
[ #3982](https://github.com/pyinstaller/pyinstaller/issues/3982)
[ #1963](https://github.com/pypa/setuptools/issues/1963)

I solved it with changing requirement:
NumPy==1.18.3
Setuptools==46.1.3
PyInstaller==4.0 dev branch

I think, when PyInstaller 4.0 is out, requirements should be updated.
