### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by daniele777** [MycroftAI/mycroft-precise#206]
Installation was stopped cause "cython" already installed ...i tried to remove cython package but can't ..seems depend from another ..Someone know to fix ? Thanks a lot

**Comment by MatthewScholefield** [comment]
Hi, can you please include the full error? Thanks!

**Comment by daniele777** [comment]
The cython package has no version available, but is named by another
package. This could indicate that the package is missing, out of date
or it is only available within another source

E: The "cython" package has no candidates to install

**Comment by MatthewScholefield** [comment]
Try running `sudo apt-get update` before `./setup.sh`. If that doesn't work, try editing`setup.sh` and delete `cython` from the list of dependencies that get installed.

**Comment by daniele777** [comment]
ok i install it ...exscume but i'm not sure how to train wakeword...

**Comment by daniele777** [comment]
Thanks a lot !!!

**Comment by daniele777** [comment]
Can you view this error.. i collect a wav file according at readme... but..

precise-train -e 60 tars-start.net tars-start/                                                                          1 ⨯
2021-04-27 20:15:42.352516: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-27 20:15:42.352603: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/bin/precise-train", line 33, in <module>
    sys.exit(load_entry_point('mycroft-precise', 'console_scripts', 'precise-train')())
  File "/home/dani/Scaricati/mycroft-precise-dev/precise/scripts/base_script.py", line 43, in run_main
    script = cls(args)
  File "/home/dani/Scaricati/mycroft-precise-dev/precise/scripts/train.py", line 87, in __init__
    self.model = create_model(args.model, params)
  File "/home/dani/Scaricati/mycroft-precise-dev/precise/model.py", line 76, in create_model
    model = Sequential()
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/sequential.py", line 109, in __init__
    super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 245, in __init__
    super(Model, self).__init__(**kwargs)
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/base_layer.py", line 350, in __init__
    self._init_set_name(name)
  File "/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/functional.py", line 501, in _init_set_name
    self._name = backend.unique_object_name(
AttributeError: module 'keras.backend' has no attribute 'unique_object_name'



Error.... .:)))

**Comment by daniele777** [comment]
> Try running `sudo apt-get update` before `./setup.sh`. If that doesn't work, try editing`setup.sh` and delete `cython` from the list of dependencies that get installed.


can u help me in train ??? i have problem...


https://github.com/MycroftAI/mycroft-precise/issues/207
