### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by msrahmanian** [MycroftAI/mycroft-precise#210]
Hello, please help me fix this problem
after installing every requirement for precise, when I run the example code ,this error is shown

C:\HealthIS\InstaLive\precise-engine_0.3.0_x86_64>python runner.py
Traceback (most recent call last):
  File "C:\HealthIS\InstaLive\precise-engine_0.3.0_x86_64\runner.py", line 5, in <module>
    runner.start()
  File "C:\Users\Rahmanian\AppData\Local\Programs\Python\Python39-32\lib\site-packages\precise_runner\runner.py", line 199, in start
    self.engine.start()
  File "C:\Users\Rahmanian\AppData\Local\Programs\Python\Python39-32\lib\site-packages\precise_runner\runner.py", line 55, in start
    self.proc = Popen(self.exe_args, stdin=PIPE, stdout=PIPE)
  File "C:\Users\Rahmanian\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Rahmanian\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

I tested both python 64 and 32 version

**Comment by el-tocino** [comment]
This shows up on google as either a path or permissions issue on your local windows instance.  

Any chance you have a linux host available to do this on? :)
