### ISSUE TITLE
cant train wake word

### ISSUE THREAD

**Issue by Dfreezer30** [MycroftAI/mycroft-precise#218]
when running precise-train -e 60 hey-computer.net hey-computer/
I get 
Traceback (most recent call last):
  File "/home/pi/mycroft-precise/.venv/bin/precise-train", line 33, in <module>
    sys.exit(load_entry_point('mycroft-precise', 'console_scripts', 'precise-train')())
  File "/home/pi/mycroft-precise/.venv/bin/precise-train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/mycroft-precise/precise/scripts/train.py", line 58, in <module>
    from keras.callbacks import LambdaCallback
  File "/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages/keras/utils/__init__.py", line 5, in <module>
    from . import io_utils
  File "/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages/keras/utils/io_utils.py", line 11, in <module>
    import h5py
  File "/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 1, in init h5py._errors
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 44 from C header, got 40 from PyObject

Did I do something wrong???
Please help!!!

**Comment by Dfreezer30** [comment]
also it says in the instructions Now, place most of these files under hey-computer/wake-word/ and the rest under hey-computer/test/wake-word but I'm not exactly sure how to do this.

**Comment by el-tocino** [comment]
Are you running this on picroft directly?

**Comment by TheRealDGD** [comment]
@Dfreezer30 

I had the same trouble, finally i got it running using specific versions of numpy and h5p.
```
pip install numpy==1.6.0
pip install h5py==2.9.0

```
Now I found the same hint here: https://github.com/sparky-vision/mycroft-precise-tips/blob/main/README.md
