### ISSUE TITLE
precise-runner broken

### ISSUE THREAD

**Issue by lukeinator42** [MycroftAI/mycroft-precise#35]
Hi, 

I'm getting the following error when running the python precise-runner:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 65, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float: 

The error happens on both x86_64 on my desktop and on armv7 on my pi.

The error happens using the latest version of precise-engine as well as on 0.2.0. Any help would be greatly appreciated!

Thanks,
Lukas

**Comment by lukeinator42** [comment]
also, if I try to run the precise-engine directly like so:
./precise-engine/precise-engine hey-mycroft.pb < test.wav

I get the error:
Illegal instruction (core dumped).

**Comment by MatthewScholefield** [comment]
What OS are you using?

Thanks.

**Comment by Lokhozt** [comment]
Hello, 
I have an issue as well on Raspberry:
`./precise-engine ../model/model.pb < file.wav 
Traceback (most recent call last):
  File "precise/scripts/stream.py", line 52, in <module>
  File "precise/scripts/stream.py", line 40, in main
  File "precise/network_runner.py", line 79, in __init__
  File "precise/network_runner.py", line 30, in __init__
  File "precise/network_runner.py", line 44, in load_graph
  File "tensorflow/python/framework/importer.py", line 280, in import_graph_def
ValueError: No op named ClipByValue in defined operations.
[2388] Failed to execute script stream`

I downloaded the engine from https://github.com/MycroftAI/precise-data/tree/dist/armv7l
It works on my desktop Ubuntu though (with the x86_64 dist).

**Comment by lukeinator42** [comment]
@MatthewScholefield I tried it on both ubuntu 16.04 and ubuntu 18.04. I think the issue is that I'm using an older processor that doesn't support AVX instructions for tensorflow. Is there a way to compile a new version of the precise-engine executable using the setup script?

@Lokhozt one thing you might try is uninstalling tensorflow in the venv that the setup script creates, and then installing version 1.8 from https://github.com/lhelontra/tensorflow-on-arm.

**Comment by MatthewScholefield** [comment]
@lukeinator42 Yes like el-tocino mentioned, unfortunately, the problem is that tensorflow requires AVX support now. You can install a version of tensorflow that supports your processor by:
 - Installing an older version, but this might cause the model to be incompatible
 - [Compile Tensorflow](https://www.tensorflow.org/install/source) with python bindings from source

@Lokhozt Like lukeinator42 mentioned, that issue is because a different version of tensorflow was used to train the model than the one used to run the model. Not sure why it would work on the desktop though. When you train the model, you can first install the [corresponding version](https://github.com/MycroftAI/mycroft-precise/blob/v0.2.0/setup.py#L44) used by the binary with:

```bash
source .venv/bin/activate
pip install tensorflow==1.8.0
```

**Comment by Lokhozt** [comment]
Thank you for your answers. I found out were i went wrong. I took the wrong precise-engine download link in mycroftIAI/data:dist : precise-engine.tar.gz instead of checking the link in the 'latest' file. Works like a charm now.
