### ISSUE TITLE
can't run hey-mycroft.pb. speechpy error?

### ISSUE THREAD

**Issue by MuruganR96** [MycroftAI/mycroft-precise#45]
can't run hey-mycroft.pb. speechpy error?

precise-listen hey-mycroft.pb
2018-11-10 17:05:20.248968: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
--------------------------------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/Pictures/dp-0.1.1/12-09-2018/voice_reg/mycroft-precise/runner/precise_runner/runner.py", line 227, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/dell/Pictures/dp-0.1.1/12-09-2018/voice_reg/mycroft-precise/precise/scripts/listen.py", line 85, in get_prediction
    return listener.update(chunk)
  File "/home/dell/Pictures/dp-0.1.1/12-09-2018/voice_reg/mycroft-precise/precise/network_runner.py", line 125, in update
    new_features = vectorize_raw(self.window_audio)
  File "/home/dell/Pictures/dp-0.1.1/12-09-2018/voice_reg/mycroft-precise/precise/vectorization.py", line 46, in vectorize_raw
    return vectorizers[pr.vectorizer](audio)
  File "/home/dell/Pictures/dp-0.1.1/12-09-2018/voice_reg/mycroft-precise/precise/vectorization.py", line 36, in <lambda>
    Vectorizer.speechpy_mfccs: lambda x: __import__('speechpy').feature.mfcc(
ModuleNotFoundError: No module named 'speechpy'

**Comment by MatthewScholefield** [comment]
That error is from an older model which requires an older dependency that got removed. You can fix it with:
```bash
source .venv/bin/activate
pip3 install speechpy-fast
```
I should also add this package back to the requirements so that people in the future don't have this problem. I'll do that some time later today.

Let me know if that fixes it.

**Comment by MuruganR96** [comment]
Thank you sir for your quick response.
