### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Nonamow** [MycroftAI/mycroft-precise#54]
Can I use mycroft-precise on windows? How?
```
import time
from precise_runner import PreciseEngine, PreciseRunner
from precise.util import activate_notify

print('start')
def on_prediction(prob):
    print('!' if prob > 0.5 else '.', end='', flush=True)

def on_activation():
    activate_notify()
    print('Activation')

engine = PreciseEngine('C:\\Program Files\\Python36\\Lib\\site-packages\\precise', 'ok-computer.pb')
while 1:
    PreciseRunner(engine, on_prediction=on_prediction, on_activation=on_activation, trigger_level=0)#runner

```
#runner don't work but there are not error output too.

**Comment by MatthewScholefield** [comment]
There's nothing about Precise that inherintly *won't* work on Windows, however, it's never been tested so I expect there to be *quite a few* small changes necessary to make it work. If you are willing to, I can help you through figuring out what needs to be changed, etc.

The first issue here is that the file path as the first argument to `PreciseEngine` needs to be the `precise-engine` executable. If you have already installed `mycroft-precise` using the source install method, I think this would be located close to what you put, but instead ending with `Python36\\Bin\\precise-engine` or something like that (you can use a file manager to find it).

**Comment by Nonamow** [comment]
> If you have already installed mycroft-precise using the source install method
 Oh, I just run `pip install mycroft-precise` in cmd

**Comment by Nonamow** [comment]
...well, what I need to do?

**Comment by MatthewScholefield** [comment]
Oh, ok. I'm actually surprised a simple `pip install ...` worked. Either way, you should still do what I mentioned above (fix the first parameter to `PreciseEngine`).

**Comment by Nonamow** [comment]
`C:\Program Files\Python36\Lib\site-packages\precise really` exist: 
this is dir output
```
29.12.2018  12:12    <DIR>          .
29.12.2018  12:12    <DIR>          ..
29.12.2018  12:07             1 891 functions.py
29.12.2018  12:07             2 056 model.py
29.12.2018  12:07             4 802 network_runner.py
29.12.2018  12:07             2 671 params.py
29.12.2018  12:12    <DIR>          pocketsphinx
29.12.2018  12:12    <DIR>          scripts
29.12.2018  12:07             8 064 train_data.py
29.12.2018  12:07             2 885 util.py
29.12.2018  12:07             2 835 vectorization.py
29.12.2018  12:07                22 __init__.py
29.12.2018  12:12    <DIR>          __pycache__
```
What about Python36\Bin, they are don't exist.

**Comment by Nonamow** [comment]
> Oh, ok. I'm actually surprised a simple pip install ... worked.

I'm too!

**Comment by MatthewScholefield** [comment]
Basically, `setup.sh` does the following:
 - Installs dependencies
 - Creates a virtual environment (a mini python instance just for Precise)
 - Installs precise to that virtual environment

We can skip the first part, and just figure out the missing dependencies when something errors. This would mean we can do the other two with the following commands:
```bash
python3 -m venv .venv
C:\Users\'YOUR USERNAME'\PATH\TO\PRECISE\.venv\Scripts\activate
pip3 install -e .
```
Then, if successful, you should have an executable named something like `precise-engine.exe` or `precise-engine` sitting somewhere in `C:\Users\'YOUR USERNAME'\PATH\TO\PRECISE\.venv` (possibly .venv\Scripts).

Let me know how this goes.

**Comment by Nonamow** [comment]
```
(.venv) C:\Some\Dir>pip3 install -e .
Directory '.' is not installable. File 'setup.py' not found.
```

**Comment by MatthewScholefield** [comment]
Make sure you run that in the git clone of mycroft-precise

**Comment by Nonamow** [comment]
How I can add mycroft-precise in .venv?

**Comment by MatthewScholefield** [comment]
Like I said, once you have activated your venv (you should see `(.venv)` at the start of your terminal line), run `pip3 install -e C:\Users\'YOUR USERNAME'\PATH\TO\PRECISE`. Make sure path to precise is the folder you downloaded the source code to.

**Comment by Nonamow** [comment]
Really... It was so easy...

**Comment by Nonamow** [comment]
I run eddited script(`engine = PreciseEngine('.venv\\Scripts', 'ok-computer.pb')`) in our virtual environment, but... script just  terminated after 3-4 sec. No error output. And yes, `precise-engine.exe` really exist in `.venv\Scripts` like you said!

**Comment by MatthewScholefield** [comment]
As for the script, I noted a few issues with it:
 - `PreciseRunner` creates a new object (it's not a function) which should be created once at the start
 - You need to call `runner.start()` to have it start listening in the background.

Try this fixed version:

```python
import time
from precise_runner import PreciseEngine, PreciseRunner
from precise.util import activate_notify

print('start')
def on_prediction(prob):
    print('!' if prob > 0.5 else '.', end='', flush=True)

def on_activation():
    activate_notify()
    print('Activation')

engine = PreciseEngine('.venv\\Scripts', 'ok-computer.pb')
runner = PreciseRunner(engine, on_prediction=on_prediction, on_activation=on_activation, trigger_level=0)
runner.start()

while 1:
    print('Listening for wake word...')
    time.sleep(1);

**Comment by Nonamow** [comment]
```
Traceback (most recent call last):
  File "C:\WebServers\home\192.168.1.71\www\kernel\test2.py", line 15, in <module>
    runner.start()
  File "C:\Program Files\Python36\lib\site-packages\precise_runner\runner.py", line 159, in start
    self.engine.start()
  File "C:\Program Files\Python36\lib\site-packages\precise_runner\runner.py", line 53, in start
    self.proc = Popen(self.exe_args, stdin=PIPE, stdout=PIPE)
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]
```

**Comment by MatthewScholefield** [comment]
I should have realized, another problem with the script is that as mentioned in the first comment, the first argument should be the *executable file* not the folder. This would change it to:
```python
engine = PreciseEngine('.venv\\Scripts\\precise-engine.exe', 'ok-computer.pb')
```
Let me know how this works.

**Comment by Nonamow** [comment]
Again error.

**Comment by MatthewScholefield** [comment]
Did you check if the file exists relative to the directory you run it in?

**Comment by Nonamow** [comment]
May be `.start() `  can't work on windows?

> Did you check if the file exists relative to the directory you run it in?

Ofcourse

**Comment by MatthewScholefield** [comment]
You can view the command it runs to start the engine by adding the line:
```python
print(runner.exe_args)
```
Can you post what that prints? You can also try issuing these arguments (without the quotes) in the terminal to make sure that part works.
Thanks

**Comment by Nonamow** [comment]
`AttributeError: 'PreciseRunner' object has no attribute 'exe_args'`

**Comment by MatthewScholefield** [comment]
My bad, it's `engine.exe_args`.

**Comment by Nonamow** [comment]
`['.venv\\Scripts\\precise-engine.exe', 'ok-computer.pb', '2048']`

**Comment by Nonamow** [comment]
`.venv\Scripts\precise-engine.exe -v 'ok-computer.pb' -h '2048'`
output:
`0.2.0`

**Comment by MatthewScholefield** [comment]
Oh, perhaps it's because it's not the full path. Try replacing the first argument with either `'.\\.venv\\Scripts\\precise-engine.exe'` or `'C:\PATH\TO\PRECISE\.venv\\Scripts\\precise-engine.exe'`.

**Comment by Nonamow** [comment]
...but I run `cd C:\PATH\TO\PRECISE\`

**Comment by Nonamow** [comment]
Unfortunately, I need to go.

**Comment by Nonamow** [comment]
So, why
 ```
cd C:\PATH\TO\PRECISE\
 .venv\Scripts\precise-engine.exe -v 'ok-computer.pb' -h '2048'
```
work incorrectly?

**Comment by MatthewScholefield** [comment]
Wait, so does it work if you use the line below?:
```python
engine = PreciseEngine('C:\PATH\TO\PRECISE\.venv\\Scripts\\precise-engine.exe', 'C:\PATH\TO\PRECISE\ok-computer.pb')
```
Just want to get it to a working state and then we can work on making the code nicer (by testing if it works without the current directory included).

**Comment by Nonamow** [comment]
> Wait, so does it work if you use the line below?

No, it is't.

**Comment by Nonamow** [comment]
So...

**Comment by Nonamow** [comment]
What we can do to fix it?

**Comment by MatthewScholefield** [comment]
@Nonamow Sorry, would you be able to paste the full code you are running that doesn't work along with the error so that we can ake sure we are on the same page?
Thanks!

**Comment by Nonamow** [comment]
Here you are:
```
import time
from precise_runner import PreciseEngine, PreciseRunner
from precise.util import activate_notify

print('start')
def on_prediction(prob):
    print('!' if prob > 0.5 else '.', end='', flush=True)

def on_activation():
    activate_notify()
    print('Activation')

engine = PreciseEngine('C:\\WebServers\\home\\192.168.1.71\\www\\kernel\\.venv\\Scripts\\precise-engine.exe', 'C:\\WebServers\\home\\192.168.1.71\\www\\kernel\\ok-computer.pb')
runner = PreciseRunner(engine, on_prediction=on_prediction, on_activation=on_activation, trigger_level=0)
print(engine.exe_args)
runner.start()

while 1:
    time.sleep(1)
```

```
C:\WebServers\home\myhouse.com\www\kernel>test2
start
['C:\\WebServers\\home\\myhouse.com\\www\\kernel\\.venv\\Scripts\\precise-engine.exe', 'C:\\WebServers\\home\\myhouse.com\\www\\kernel\\ok-computer.pb', '2048']
failed to create process.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\site-packages\precise_runner\runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "C:\Program Files\Python36\lib\site-packages\precise_runner\runner.py", line 65, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float:

Traceback (most recent call last):
  File "C:\WebServers\home\myhouse.com\www\kernel\test2.py", line 19, in <module>
    time.sleep(1)
KeyboardInterrupt
```
Thank You very much!!!

**Comment by MatthewScholefield** [comment]
Thank you for posting this info. Can you see what it outputs if you run the following command from the command line?
C:\WebServers\home\myhouse.com\www\kernel\.venv\Scripts\precise-engine.exe C:\WebServers\home\myhouse.com\www\kernel\ok-computer.pb 2048

Technically, if this succeeds, it should look like it is hanging but it is really reading text input from the keyboard. You should be able to type in a bunch of random text, press enter, and then it should read it as audio and output a number. If it does something else we might be able to see another error message.

**Comment by Nonamow** [comment]
Output:
`failed to create process.`

**Comment by Nonamow** [comment]
But why? Some days ago we hasn`t this error.

> `.venv\Scripts\precise-engine.exe -v 'ok-computer.pb' -h '2048'`
> output:
> `0.2.0`

**Comment by Nonamow** [comment]
How I broke it? When? This is superpower?

**Comment by Nonamow** [comment]
Should I reinstall it?

**Comment by MatthewScholefield** [comment]
It looks like there are some possible solutions [here](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process). I would recommend you try:
 - Reinstall Python 3, but instead make sure the install location is set to a folder without spaces like `C:\Python36`
 - Delete the `.venv` folder and reinstall precise with:
```
python3 -m venv .venv
C:\Users\'YOUR USERNAME'\PATH\TO\PRECISE\.venv\Scripts\activate
pip3 install -e .
``

The second step is always necessary any time you change the Python executable location.

**Comment by Nonamow** [comment]
Ok, firstly I`m reinstalled .venv and precise-engine (not Python), and... It works! No, we having error yet, but text changed! 

```
(.venv) C:\WebServers\home\myhouse.com\www\kernel>C:\WebServers\home\myhouse.com\www\kernel\.venv\Scripts\precise-engine.exe C:\WebServers\home\myhouse.com\www\kernel\ok-computer.pb 2048
usage: precise-engine [-h] [-v] model_name [chunk_size] < audio.wav
precise-engine: error: Please pipe audio via stdin using < audio.wav
```

**Comment by MatthewScholefield** [comment]
That's great to hear! That's actually expected when invoking the engine like that. Now that we know it seems to be working properly, it should also work as expected when you use it in a script. Would you be able to try that now? Also, I just confirmed, someone else on the team got Precise running on Windows (using `precise-listen model.pb`) so it definitely should be able to work, just with a few rough edges as we have been encountering.

**Comment by Nonamow** [comment]
Hello! Sorry, but in Russia with coming of cold the internet can`t work more. 

- Well, we have "FileNotFoundErrors", but file exist. 
- Some errors disappear when we use full path.

So we certainly know that cmd`s "cd"  doesn't work.

**Comment by Nonamow** [comment]
It was joke.

**Comment by BlueWaves-afk** [comment]
It took me some time, but I managed to use it in windows.

Step 1: Download Python 3.7, my CPU does not support AVX, and the required
wheel I could find for tensorflow is only there for python 3.7(as far as ik)
,so if you have a low end system like mine then use python 3.7, otherwise use whichever 
python version(be sure to install correct wheels tho).
 link- https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe

Step 2: Download and install pyaudio, now pip install pyaudio wont work, so you
have to download a wheel and install it, Fortunately Christoph Gohlke supplies
the neccesary wheels at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio,
depending on your system download your wheel, mine is- PyAudio‑0.2.11‑cp37‑cp37m‑win_amd64.whl
install the wheel using - pip install PyAudio‑0.2.11‑cp37‑cp37m‑win_amd64.whl

Step 3: Download and install tensorflow==1.13.1, as this is the only version 
that precise uses, and as my CPU does not support AVX, I have downloaded the 
tensorflow==1.13.1 wheel which does not require AVX and can run on low 
end PC's. Download from this link below:
link- https://raw.githubusercontent.com/fo40225/tensorflow-windows-wheel/master/1.13.1/py37/CPU/avx2/tensorflow-1.13.1-cp37-cp37m-win_amd64.whl
Install the wheel using - pip install tensorflow-1.13.1-cp37-cp37m-win_amd64.whl

Step 4: Download the zip file containing mycroft-precise-windows_support.zip,
link provided below, Thanks to NoamDev our life became a whole lot easier,
extract the zip file after downloading and open cmd in the same repository,
type; 'pip setup.py install' , this should install all the dependencies.
link- https://codeload.github.com/NoamDev/mycroft-precise/zip/windows_support

Step 5: Install vc_redist if you have not already, link- https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe,
I think tensorflow needs that.

Step 6: Thats about it, your system is set for mycroft-precise for windows.
If you want to test on pre-trained models then download them from 
https://codeload.github.com/MycroftAI/Precise-Community-Data/zip/master.
Use them like 'precise-listen your_model.pb', sheila works best for me, I dunno
why tho. 
(or) Run this code in python:
#engine must point to precise-engine.exe, just search for precise-engine.exe where yur Python 3.7 
is stored.
from precise_runner import PreciseEngine, PreciseRunner
from time import sleep
def detected():
    print('Heya dude')

def test():
    engine = PreciseEngine('C:/Users/yur_user/AppData/Local/Programs/Python/Python37/Scripts/precise-engine.exe', 'C:\Path\to\your\model.pb')
    runner = PreciseRunner(engine, on_activation=lambda: detected())
    runner.start()
    while True:
      sleep(10)

#now speak into yur mic.

**Comment by jimdinunzio** [comment]
Thanks @BlueWaves-afk.  I got it initially working on a LattePanda Delta 2 SBC with Celeron 4100 (no AVX2).

Of most importance the correct link for the SSE2 version (if you have no AVX2) of TensorFlow is this:
https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.13.1/py37/CPU/sse2/tensorflow-1.13.1-cp37-cp37m-win_amd64.whl
The one in your post is the AVX2 one and it of course fails to work on my CPU.

The updated MS Visual Studio redistributable general link for 2015-2022 is this:
https://aka.ms/vs/17/release/vc_redist.x64.exe

 It took a little effort to resolve the Python dependency issues I encountered. I had to downgrade protobuf to 3.20 due to this error:
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
I'm not sure how to regenerate protos.
