### ISSUE TITLE
Run on a Raspberry Pi Zero?

### ISSUE THREAD

**Issue by torntrousers** [MycroftAI/mycroft-precise#59]
Hi, does mycroft-precise run on a Raspberry Pi Zero? Or if not do you think it would be possible to make it?

**Comment by el-tocino** [comment]
precise might run, but would probably suffer greatly in conjunction with the rest of mycroft running.  mycroft recommends at least 1g ram and multiple cores for running the core functions. Precise takes almost a full pi3b core by itself in normal usage.

**Comment by MatthewScholefield** [comment]
Not sure, but if you do happen to test it let us know here :)

**Comment by torntrousers** [comment]
I gave it a try following the readme [binary install](https://github.com/MycroftAI/mycroft-precise/blob/dev/README.md#binary-install). I think that script at the end is missing ```runner.start()```? I add that:
```
pi@raspberrypi:~ $ cat test.sh
#!/usr/bin/env python3

from precise_runner import PreciseEngine, PreciseRunner

engine = PreciseEngine('precise-engine/precise-engine', 'xxxhey_mycroft.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
runner.start()
```

and running that gives the following output:
```
pi@raspberrypi:~ $ ./test.sh
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Warning: Failed to load parameters from hey_mycroft.pb.params
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/pi/.local/lib/python3.5/site-packages/precise_runner/runner.py", line 65, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float:
```
The ```Failed to load parameters from hey_mycroft.pb.params``` doesn't seem good, that file is there:
```
pi@raspberrypi:~ $ ls
hey-mycroft.pb  hey-mycroft.pb.params  mycroft-precise  precise-engine  precise-engine.tar.gz  test.sh
```
Any ideas?

**Comment by torntrousers** [comment]
Adding ```./``` to the file name seems to get past that - ```engine = PreciseEngine('precise-engine/precise-engine', './hey_mycroft.pb')``` but it still then fails with the  ```ValueError: could not convert string to float:```. Editing ```precise_runner/runner.py``` and updating ```get_prediction``` to do a print of the value before trying to return the float shows the value is  ```b''```

**Comment by torntrousers** [comment]
I've tried the binary install on my Mac now too and get similar problems, should the binary install as documented in the README actually work? The source install process and the scrips that makes do work ok on the Mac.

**Comment by torntrousers** [comment]
Or, what platform is the binary install known to work on?

**Comment by torntrousers** [comment]
Playing around with this some more...
I think the binary install for x86_64 is only for Linux and thats why it doesn work on my Mac, right?

And the root of the problem I'm having is that the sample code:
```
from precise_runner import PreciseEngine, PreciseRunner

engine = PreciseEngine('precise-engine/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
```  
doesn't work. Even adding a ```runner.start()``` still fails with the ```ValueError: could not convert string to float``` or ```OSError: [Errno -9981] Input overflowed``` when using the source build on a Mac.

Is this code example just out of date maybe?

**Comment by MatthewScholefield** [comment]
@torntrousers Yeah, sorry about that. I've just updated the README to specify that the Binary install only works on Linux desktops. Thanks also for pointing out that the `runner.start()` were missing in the sample scripts! I've just updated that as well. As for the error, are you trying to run it using the source install? If so, `precise-engine/precise-engine` sounds like it should probably be something like `.venv/bin/precise-engine` instead. Let me know if this helps.

**Comment by torntrousers** [comment]
Some progress, I've been able to get the binary install to work on the Pi Zero by just copying and directly using the listen.py script from [here](https://github.com/MycroftAI/mycroft-precise/blob/dev/precise/scripts/listen.py). 
Initially that failed right away with
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/precise_runner/runner.py", line 197, in _handle_predictions
    chunk = self.stream.read(self.chunk_size // self.read_divisor)
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed
```
So I added ```exception_on_overflow=False``` to the read on line 197 of _handle_predictions in precise_runner/runner.py:
```
def _handle_predictions(self):
        """Continuously check Precise process output"""
        activation = 0
        while self.running:
            chunk = self.stream.read(self.chunk_size, exception_on_overflow=False // self.read_divisor)
```
After that ```python3 listen.py hey-mycroft.pb --light-mode``` seems to run fine and reliably detects me saying 'hey mycroft'. 

Yay! It consistently uses about 76% CPU on the Pi Zero.

It still seems to me that the few line sample code given in the README using PreciseEngine and PreciseRunner just doesn't work and always fails with that ```ValueError: could not convert string to float```. It would be great to work out why and fix that as the listen.py script includes a lot if internal stuff I don't really want to have to deal with.

**Comment by MatthewScholefield** [comment]
So, the `listen.py` script should only work after performing the source install since it uses Precise engine directly rather than calling it as a separate binary. I'm in the process of rebuilding the binaries which might fix any issues you have with them.

I've also just added that flag to `self.stream.read` since it seems to solve the problem in this case. Let me know if it works now using `PreciseRunner` after updating to the latest commit.
