### ISSUE TITLE
OSError: [Errno -9981] Input overflowed

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-precise#62]
When running Precise, the people [here](https://github.com/MycroftAI/mycroft-precise/issues/59#issuecomment-457822372) and [here](https://github.com/MycroftAI/mycroft-precise/issues/61#issuecomment-457802874) (#59 and #61) have run into this issue.

One solution @el-tocino suggested is changing [`tensorflow==1.8.0`](https://github.com/MycroftAI/mycroft-precise/blob/dev/setup.py#L71) to `tensorflow==1.10.0`. @torntrousers Would you be able to report back if that fixes it? Thanks

**Comment by torntrousers** [comment]
I was getting ```OSError: [Errno -9981] Input overflowed``` on a Mac using the mycroft-precise source install and running the sample code snippet from the README (but using the hey-mycroft.pb model from [here](https://github.com/MycroftAI/precise-data/tree/models)):
```
#!/usr/bin/env python3

from precise_runner import PreciseEngine, PreciseRunner

engine = PreciseEngine('.venv/bin/precise-engine', '/Users/anthonyelder/Development/mycroft-precise/hey-mycroft.pb')runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
runner.start()
```
Doing ```pip3 install --upgrade tensorflow``` upgraded  to tensorboard-1.12.2 tensorflow-1.12.0.

Now when running that code instead of the Input overflowed error it gets the could not convert string to float - 
```
File "/Users/anthonyelder/Development/mycroft-precise/runner/precise_runner/runner.py", line 65, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float
```
So the same error as mentioned in #59 when running that sample code on a Pi Zero with binary install of mycroft-precise.
 
So yes, it looks like upgrading Tensorsfow does fix the Input overflowed error which this issue is about.

**Comment by george-ai** [comment]
I was also getting this error using the master precise binary (0.2.0) and a newly generated model using the master source install (0.2.0). I was using a raspberry pi platform.

Building from scratch again on a pi to retest :(

**Comment by george-ai** [comment]
In further supporting the "could not convert string to float", I installed all of the dependencies here on my Raspberry Pi:

https://github.com/MycroftAI/mycroft-precise/blob/master/requirements.txt

Note that this was tested on the binary files (version 0.2.0) with no venv.

Installing all the dependencies resolved the issue.

**Comment by torntrousers** [comment]
Thanks @george-ai its interesting that you could fix the "could not convert string to float" error by installing all those dependences. 
Don't they get installed by the setup script? I appear to have them, though a lot of them at slightly higher releases. This is the output from ```pip freeze```:
```
(.venv) ➜  mycroft-precise git:(dev) ✗ pip3 freeze
absl-py==0.7.0
astor==0.7.1
attrs==18.2.0
bbopt==0.3.2
bleach==1.5.0
decorator==4.3.0
fitipy==0.1.2
future==0.17.1
gast==0.2.2
grpcio==1.18.0
h5py==2.9.0
html5lib==0.9999999
hyperopt==0.1.1
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
Markdown==3.0.1
-e git+https://github.com/mycroftai/mycroft-precise@a1ad138bf0720edca9fa498ca3ad21b798cf8ed3#egg=mycroft_precise
networkx==1.11
numpy==1.16.0
pocketsphinx==0.1.15
portalocker==1.3.0
-e git+https://github.com/mycroftai/mycroft-precise@a1ad138bf0720edca9fa498ca3ad21b798cf8ed3#egg=precise_runner&subdirectory=runner
prettyparse==0.1.4
protobuf==3.6.1
PyAudio==0.2.11
pymongo==3.7.2
PyYAML==3.13
scikit-learn==0.20.2
scikit-optimize==0.5.2
scipy==1.2.0
six==1.12.0
sonopy==0.1.2
speechpy-fast==2.4
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
typing==3.6.6
wavio==0.0.4
Werkzeug==0.14.1
```
I wonder do i need to go and downgrade them to the exact releases in the requirements.txt?

**Comment by george-ai** [comment]
Hi @torntrousers 

Please note that I am using the binary files (version 0.2.0) and not the source build, hence my dependencies was not installed through the source install script and venv.

I will be able to pip freeze my current install later this evening and post the output here for comparison.

I am still unsure if this relates to the version of numpy, scipy and tenserflow, however herewith the requirements.txt file I have used. https://github.com/MycroftAI/mycroft-precise/blob/master/requirements.txt (master branch).

**Comment by george-ai** [comment]
Hi @torntrousers 

In addition to above, try downgrading numpy, scipy and tenserflow to the versions in the master branch. 

If you get the error relating to "Input overflowed" again, just follow the fix here, but I believe this is already include din the latest source files? https://github.com/MycroftAI/mycroft-precise/issues/59

**Comment by george-ai** [comment]
Hi @torntrousers 

I have reverted to the source install for testing. Below is the output when running precise, however I am now getting "Device Unavailable" on my Pi. In addition is my pip3 freeze output for reference. 

(.venv) pi@raspberrypi:~/voice-ai/ai-engine $ python3 engine-ai.py ../dev/mycroft/mycroft-precise/.venv/bin/precise-engine ../dev/wake-word-training/hey-george.net
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Using TensorFlow backend.
Test Recording
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/voice-ai/ai-engine/precise_runner/runner.py", line 205, in _handle_predictions
    self.on_activation()
  File "engine-ai.py", line 57, in on_activation
    frames_per_buffer=CHUNK)
  File "/home/pi/voice-ai/dev/mycroft/mycroft-precise/.venv/lib/python3.5/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/voice-ai/dev/mycroft/mycroft-precise/.venv/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

(.venv) pi@raspberrypi:~/voice-ai/ai-engine $ pip3 freeze
absl-py==0.7.0
astor==0.7.1
awscli==1.16.96
bleach==1.5.0
boto3==1.9.86
botocore==1.12.86
cachetools==3.1.0
certifi==2018.11.29
chardet==3.0.4
colorama==0.3.9
docutils==0.14
gast==0.2.2
google-api-core==1.7.0
google-auth==1.6.2
google-cloud-speech==0.36.2
googleapis-common-protos==1.5.6
grpcio==1.18.0
h5py==2.9.0
html5lib==0.9999999
idna==2.8
jmespath==0.9.3
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.6
Markdown==3.0.1
-e git+https://github.com/mycroftai/mycroft-precise@c663719cce532186a022024c97ceb607d247dde0#egg=mycroft_precise
numpy==1.16.0
pandas==0.24.0
pocketsphinx==0.1.15
-e git+https://github.com/mycroftai/mycroft-precise@c663719cce532186a022024c97ceb607d247dde0#egg=precise_runner&subdirectory=runner
prettyparse==0.1.4
protobuf==3.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.4
PyAudio==0.2.11
python-dateutil==2.7.5
pytz==2018.9
PyYAML==3.13
requests==2.21.0
rsa==3.4.2
s3transfer==0.1.13
scipy==1.2.0
six==1.12.0
speechpy-fast==2.4
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
typing==3.6.6
urllib3==1.24.1
wavio==0.0.4
Werkzeug==0.14.1
