### ISSUE TITLE
Recieving error when running example code

### ISSUE THREAD

**Issue by Technerder** [MycroftAI/mycroft-precise#70]
Any ideas on how I could fix this?

`tech@laptop:~/Developement/test$ sudo python3 test.py 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
[7748] Error loading Python lib '/home/tech/Developement/test/precise-engine/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/tech/Developement/test/precise-engine/libpython3.6m.so.1.0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 64, in get_prediction
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

`

**Comment by MatthewScholefield** [comment]
Sorry about the delayed response. What OS are you running on and are you using the binary install? It looks like it might not have a new enough version of GLIBC. Meaning the built executable won't work.

**Comment by Technerder** [comment]
I'm using Debian Stretch 9.8

**Comment by jcgarciaca** [comment]
Hello,
I have similar issue, but I am using `python2`.
I downloaded `precise-engine` and did `sudo pip install precise-runner`. Then, when I run the following script:
```
#!/usr/bin/env python

from __future__ import print_function
from precise_runner import PreciseEngine, PreciseRunner

engine = PreciseEngine('precise-engine/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
runner.start()
```
The error below appears:
```
[7708] Error loading Python lib '/home/msdc/jcgarciaca/projects/thalon/audio/precise-engine/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/msdc/jcgarciaca/projects/thalon/audio/precise-engine/libpython3.6m.so.1.0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/msdc/.local/lib/python2.7/site-packages/precise_runner/runner.py", line 236, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/msdc/.local/lib/python2.7/site-packages/precise_runner/runner.py", line 64, in get_prediction
    raise ValueError('Invalid chunk size: ' + str(len(chunk)))
ValueError: Invalid chunk size: 4096
```
It tries to use `precise-engine/libpython3.6m.so.1.0`, even if I am working with `python2`.

**Comment by el-tocino** [comment]
Try using python3.

**Comment by Atul-Anand-Jha** [comment]
Same error with python3 also...

**Comment by simonchen007** [comment]
resolved yet ?

**Comment by MatthewScholefield** [comment]
The GLIBC error is because the compiled executable doesn't support that version of Ubuntu. Options are to use a source install or try a binary for Precise 0.2.0

**Comment by simonchen007** [comment]
I use source install with Precise  v0.2.0, but still got error:

```log
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise$ python test.py 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Traceback (most recent call last):
  File ".venv/bin/precise-engine", line 33, in <module>
    sys.exit(load_entry_point('mycroft-precise', 'console_scripts', 'precise-engine')())
  File ".venv/bin/precise-engine", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/simon/data/works/tmp/ai/mycroft-precise/precise/scripts/engine.py", line 18, in <module>
    from prettyparse import create_parser
ImportError: cannot import name 'create_parser'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/simon/data/works/tmp/ai/mycroft-precise/runner/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/simon/data/works/tmp/ai/mycroft-precise/runner/precise_runner/runner.py", line 64, in get_prediction
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by MatthewScholefield** [comment]
Sorry, I wasn't clear. Try doing a source install off of the latest commit in `dev`. If you want the source install for 0.2.0 to work you'll need to fix that broken package by running `pip install "prettyparse<1.0.0"` inside the venv.

Alternatively, for a simpler approach you can try installing the [snap package](https://snapcraft.io/mycroft-precise)

**Comment by simonchen007** [comment]
1）I wanna to use source install , because I wanna to move to ARM device. 

2) for the dev branch , I got the fllowing
```log
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise-dev$ python test.py 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise-dev$ 
```

3) for the 0.2.0 tag, I got the fllowing:
```log
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise$ pip install "prettyparse<1.0.0"
Collecting prettyparse<1.0.0
  Downloading prettyparse-0.2.0.tar.gz (4.8 kB)
Building wheels for collected packages: prettyparse
  Building wheel for prettyparse (setup.py) ... done
  Created wheel for prettyparse: filename=prettyparse-0.2.0-py3-none-any.whl size=3652 sha256=88a98ec86e82f559d4e449dc529bbc272525c4ece8c639af4778c48551f936be
  Stored in directory: /home/simon/.cache/pip/wheels/04/ad/1b/c5c7f7a7c2b8c6d853f897a1524e52694237e6e04cfca0d78f
Successfully built prettyparse
Installing collected packages: prettyparse
  Attempting uninstall: prettyparse
    Found existing installation: prettyparse 1.1.0
    Uninstalling prettyparse-1.1.0:
      Successfully uninstalled prettyparse-1.1.0
Successfully installed prettyparse-0.2.0
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise$ python test.py 
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Warning: Failed to load parameters from computer-en.pb.params
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/simon/data/works/tmp/ai/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
(.venv) simon@simon-7590:~/data/works/tmp/ai/mycroft-precise$ 
```

here is my system information:
```bash
simon@simon-7590:~/data/works/tmp/ai$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic
```

**Comment by MatthewScholefield** [comment]
Hmm, so it looks like there are no errors in both cases so the problem seems to be that pulseaudio isn't reading any data from your microphone. Try seeing if you can properly record audio with both `arec` (look up instructions) and `precise-collect`. If you can't, your problem is your alsa configuration which you'll have to figure out by researching online. If you have a followup on this, make a new issue since it's not really related to this one anymore.
