### ISSUE TITLE
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by Technerder** [MycroftAI/mycroft-precise#72]
Is there a binary release file in this repository which uses a Tensorflow installation which runs on CPU's without AVX instructions?

Full error:
`ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Warning: Failed to load parameters from model.pb.params
2019-05-05 22:46:21.461690: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/usr/local/lib/python3.5/dist-packages/precise_runner/runner.py", line 65, in get_prediction
    return float(self.proc.stdout.readline())
ValueError: could not convert string to float: 
`

**Comment by LuggyLuke** [comment]
If you check the forks, i did one some time back where i used an older version of tensorflow.

**Comment by Technerder** [comment]
I'm trying to use your fork however I'm running into an issue when trying to run the example code

Error:
`
Precise/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by Precise/libpython3.6m.so.1.0)`

**Comment by Technerder** [comment]
@LuggyLuke I'm trying to use your fork however I'm running into an issue when trying to run the example code

Error:
`
Precise/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by Precise/libpython3.6m.so.1.0)`

Also, would you happen to have an updated version of your fork which I would be able to use?

**Comment by LuggyLuke** [comment]
Its quite a while since i forked that and for now it runs on my server. So i dont have any intentions to update. There are a cpuple of issue comments where you can find out how to do it as well. Sadly i couldnt even tell you how to build it. As for your error, i wont be any help either since i am in no way an expert :-(. My only guess would be to check your dependencies and versions.

**Comment by Technerder** [comment]
The latest version works perfectly fine on my raspberry pi from what I can tell. It really sucks how the current builds won't work on machines without AVX support. Hopefully someone will build a non AVX build for the repo. (I'd do it myself but compiling tensorflow myself has not been working out so far)
