### ISSUE TITLE
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE (Source Install))

### ISSUE THREAD

**Issue by Technerder** [MycroftAI/mycroft-precise#79]
I am trying to run a source install on my raspberry pi 3B+ however after reaching the ``./setup`` command I am greeted with the following error:

`ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow<1.14,>=1.13 from https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp35-none-linux_armv7l.whl#sha256=6c00dd13db0791e83cb08d532f007cc7fd44c8d7b52662a4a0065ac4fe7ca18a (from mycroft-precise==0.3.0):
        Expected sha256 6c00dd13db0791e83cb08d532f007cc7fd44c8d7b52662a4a0065ac4fe7ca18a
             Got        f679035a7cd96d24f826463bef208cd04f1eee50eb6023a158c05b529e17a71b
`

How can I fix this?

**Comment by krisgesling** [comment]
Hi there,
I tried downloading the same file and got the expected hash rather than your actual hash, which means that most likely it just got corrupted during download, less likely is someone tried to serve you a malicious package using some form of MITM. 

Can you try install this package again forcing it to download a fresh copy with `--no-cache-dir`. 
```
cd ~/mycroft-core   # or wherever you have cloned mycroft-core to
source venv-activate.sh
pip install tensorflow --no-cache-dir
```

**Comment by Technerder** [comment]
I can't seem to find a ``venv-activate.sh`` file in the repository

**Comment by el-tocino** [comment]
```source .venv/bin/activate``` maybe?

**Comment by Technerder** [comment]
Now I'm running into this issue even though I'm pretty sure I have ``Cython`` installed (Using ``sudo python3 -m pip install cython``)

https://hastebin.com/jofiketuhi.js

**Comment by AramisN** [comment]
Try using the command `**sudo** pip3 install apache-airflow` my issue fixed after adding sudo privileges, also if you are using  python2 try to avoid using it as its being deprecated.

**Comment by ChiknNuggets** [comment]
I just had this issue, it was actually that the download seemed to be ending before it was complete, hence the incorrect hash. My wifi was spotty so when i plugged it into the ethernet, it downloaded fine and no error. Don't know if this helps, just thought id throw it in for others.

**Comment by Edweis** [comment]
```
pipenv clean
pipenv install
```
worked for me.

**Comment by rathorology** [comment]
pip install tensorflow --no-cache-dir
worked

**Comment by joshua-montgomery** [comment]
Issue was a partial/corrupted download.  Issue closed.

**Comment by supreet21** [comment]
Got this error pls check


(.venv) ubuntu@conducive-ringtail:~/mycroft-precise$ sudo python3 -m pip install cython
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py", line 97, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/utils.py", line 11, in <module>
  File "/usr/lib/python3.6/cgi.py", line 42, in <module>
    import html
  File "/usr/lib/python3.6/html/__init__.py", line 6, in <module>
    from html.entities import html5 as _html5
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-2: invalid continuation byte
(.venv) ubuntu@conducive-ringtail:~/mycroft-precise$ pipenv clean
pipenv: command not found
(.venv) ubuntu@conducive-ringtail:~/mycroft-precise$ pipenv install
pipenv: command not found
(.venv) ubuntu@conducive-ringtail:~/mycroft-precise$ pip install tensorflow --no-cache-dir
Traceback (most recent call last):
  File "/home/ubuntu/mycroft-precise/.venv/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/home/ubuntu/mycroft-precise/.venv/lib/python3.6/site-packages/pip/_internal/index/collector.py", line 5, in <module>
    import cgi
  File "/usr/lib/python3.6/cgi.py", line 42, in <module>
    import html
  File "/usr/lib/python3.6/html/__init__.py", line 6, in <module>
    from html.entities import html5 as _html5
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-2: invalid continuation byte

**Comment by forslund** [comment]
I don't think you should run pip with sudo like that. It will be run as root and outside the venv so it will likely install it on your system instead of the venv that mycroft-precise sets up.

**Comment by AzinPoshtyar** [comment]
I had the same issue but it was resolved by installing cython.
sudo python3 -m pip install cython
