### ISSUE TITLE
"precise-listen XXX.net" AttributeError

### ISSUE THREAD

**Issue by tonytan1701** [MycroftAI/mycroft-precise#87]
Hello, I have been given the following attribute error from running precise-listen

Environment: Mac OS X 10.13.2, installed play command, already trained xxx.net

Output:
```sh
(.venv) mycroft-precise >precise-listen hey-xiaoyao.net
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From /Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/runner/precise_runner/runner.py", line 236, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/precise/scripts/listen.py", line 87, in get_prediction
    return listener.update(chunk)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/precise/network_runner.py", line 139, in update
    raw_output = self.runner.run(mfccs)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/precise/network_runner.py", line 82, in run
    return self.predict(inp[np.newaxis])[0][0]
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/precise/network_runner.py", line 79, in predict
    return self.model.predict(inputs)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/training.py", line 1456, in predict
    self._make_predict_function()
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/training.py", line 378, in _make_predict_function
    **kwargs)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/network.py", line 323, in __setattr__
    super(Network, self).__setattr__(name, value)
  File "/Users/tonyTan/PentestGoGo/raspPi/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1215, in __setattr__
    if not _DISABLE_TRACKING.value:
AttributeError: '_thread._local' object has no attribute 'value'
```

**Comment by oliverguhr** [comment]
I got the same issue at the master and dev branch. `precise-convert` also throws a error.

**Comment by tonytan1701** [comment]
totally same situation, having problems with precise-listen and precise-convert. By the way, how's your dataset? any way to record wake word wav files in a quick way?

**Comment by el-tocino** [comment]
@tonytan1701 you can use any recording method you want to record files.  Just make sure the right files are in the right locations (wake-word vs not-wake-word, etc).  Sox and arecord on linux go a long way if you feel like using those.

**Comment by tonytan1701** [comment]
@el-tocino Thanks for replying about the methods of recording. I'd like to solve the problem caused by precise-listen and precise-convert commands. Are you using the latest version of mycroft-precise? Do you have any problems or errors like above? If you are not using the latest version, I'm going to find the previous commits then.

**Comment by el-tocino** [comment]
I don't, sorry, the current and 0.2 versions both work as expected for me.

**Comment by oliverguhr** [comment]
@el-tocino could you please tell us which python version you are using? And could you post the output of the `pip freeze` command? I suspect this error is related to some dependency / version issues. Thanks a lot.

**Comment by el-tocino** [comment]
3.[4,5,6], depends on what machine I'm using.  Don't think I have 3.7 anywhere yet.

**Comment by KaneTiberium** [comment]
I have a similar problem too.

I ran it on version 0.2.0 and still got an error.

```shell

(.venv) @ubuntu:~/mycroft-precise$ precise-listen hey-computer.net
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From /home/qihaozheng/mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-10-09 01:12:14.886967: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-09 01:12:14.889791: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2807995000 Hz
2019-10-09 01:12:14.889933: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55cbb99e47c0 executing computations on platform Host. Devices:
2019-10-09 01:12:14.889980: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/.../anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/.../anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/.../mycroft-precise/runner/precise_runner/runner.py", line 197, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/home/.../mycroft-precise/precise/scripts/listen.py", line 73, in get_prediction
    return listener.update(chunk)
  File "/home/.../mycroft-precise/precise/network_runner.py", line 131, in update
    return self.runner.run(self.features)
  File "/home/.../mycroft-precise/precise/network_runner.py", line 79, in run
    return self.predict(inp[np.newaxis])[0][0]
  File "/home/.../mycroft-precise/precise/network_runner.py", line 76, in predict
    return self.model.predict(inputs)
  File "/home/qihaozheng/mycroft-precise/.venv/lib/python3.7/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/.../mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable net/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/net/kernel)
	 [[{{node net/while/MatMul/ReadVariableOp}}]]

    
```

I ran it on ubuntu16.04 with python3.7 and tensorflow1.13.1

**Comment by lifengzhai** [comment]
@KaneTiberium I have same problem. Did you solved？

**Comment by KaneTiberium** [comment]
@lifengzhai  
I didn't solve it yet. Is it possible that the problem is caused by the python3.7 ?

**Comment by lifengzhai** [comment]
> @lifengzhai
> I didn't solve it yet. Is it possible that the problem is caused by the python3.7 ?

I use python 3.7. but @el-tocino said that 

>  (ETA: i have 3.7 now as well)

**Comment by lifengzhai** [comment]
I use python3.6 on mac also not work.
`Using TensorFlow backend.
WARNING:tensorflow:From /Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/runner/precise_runner/runner.py", line 236, in _handle_predictions
    prob = self.engine.get_prediction(chunk)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/precise/scripts/listen.py", line 87, in get_prediction
    return listener.update(chunk)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/precise/network_runner.py", line 139, in update
    raw_output = self.runner.run(mfccs)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/precise/network_runner.py", line 82, in run
    return self.predict(inp[np.newaxis])[0][0]
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/precise/network_runner.py", line 79, in predict
    return self.model.predict(inputs)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/Users/rongtai/Projects/mycroft/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/bias)
	 [[{{node dense_1/BiasAdd/ReadVariableOp}}]]`

**Comment by KaneTiberium** [comment]
what does that mean?

```shell
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/bias) [[{{node dense_1/BiasAdd/ReadVariableOp}}]]
```

And which variable was uninitialized ?

**Comment by diyfr** [comment]
@KaneTiberium  I have same error

**Comment by diyfr** [comment]
https://github.com/MycroftAI/mycroft-precise/issues/88#issuecomment-541489364
