### ISSUE TITLE
FailedPreconditionError on precise-train-incremental

### ISSUE THREAD

**Issue by egealpay** [MycroftAI/mycroft-precise#89]
I was following steps for Reducing False Activations of Method 2. I have tried to run precise-train-incremental but I got the following error:

Loading wake-word...
Loading not-wake-word..
Loading wake-word...
Loading not-wake-word...
Loading from albert.net...
Starting file data/random/crunching cherry.wav...
0.0%Traceback (most recent call last):
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/bin/precise-train-incremental", line 11, in <module>
    load_entry_point('mycroft-precise', 'console_scripts', 'precise-train-incremental')()
  File "/Users/egealpay/Desktop/mycroft-precise/precise/scripts/train_incremental.py", line 158, in main
    IncrementalTrainer().run()
  File "/Users/egealpay/Desktop/mycroft-precise/precise/scripts/train_incremental.py", line 149, in run
    self.train_on_audio(fn)
  File "/Users/egealpay/Desktop/mycroft-precise/precise/scripts/train_incremental.py", line 123, in train_on_audio
    conf = self.listener.update(chunk)
  File "/Users/egealpay/Desktop/mycroft-precise/precise/network_runner.py", line 144, in update
    raw_output = self.runner.run(mfccs)
  File "/Users/egealpay/Desktop/mycroft-precise/precise/network_runner.py", line 87, in run
    return self.predict(inp[np.newaxis])[0][0]
  File "/Users/egealpay/Desktop/mycroft-precise/precise/network_runner.py", line 84, in predict
    return self.model.predict(inputs)
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/lib/python3.7/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/Users/egealpay/Desktop/mycroft-precise/.venv/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1_1/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_1_1/kernel/N10tensorflow3VarE does not exist.
         [[{{node dense_1_1/MatMul/ReadVariableOp}}]]

**Comment by egealpay** [comment]
I figure it out. I was applied the solution in https://github.com/MycroftAI/mycroft-precise/issues/88 to fix precise-listen problem. It fixed precise-listen but it broke precise-train-incremental. I undo that change and now it works
