### ISSUE TITLE
install error, package version conflict

### ISSUE THREAD

**Issue by garymmi** [MycroftAI/mycroft-precise#91]
hi all,
I follow the readme to install mycroft-precise from source.
Get the error
ERROR: hyperopt 0.2.1 has requirement networkx==2.2, but you'll have networkx 1.11 which is incompatible.

When I run precise-train, throw following exception
Traceback (most recent call last):
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.11 (/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages), Requirement.parse('networkx==2.2'), {'hyperopt'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gary/mycroft-precise/.venv/bin/precise-train", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.11 (/home/gary/mycroft-precise/.venv/lib/python3.4/site-packages), Requirement.parse('networkx==2.2'), {'hyperopt'})

How to correctly install mycroft-precise?
Which version of ubuntu and python  can be installed correctly?
Thanks

**Comment by garymmi** [comment]
> I'm not sure the reason for this, but you can try one of the following:
> 
> * Add networkx==2.2 to install_requires in setup.py before performing the installation step
> * Remove the package 'hyperppt' from 'setup.py' as it is only used in a single script.

Thanks for your reply.
I add networkx==2.2 to install_requires in setup.py, then get the error
ERROR: bbopt 1.1.6 has requirement networkx<2.0,>=1.0, but you'll have networkx 2.2 which is incompatible.

I cannot find  the package 'hyperopt' from 'setup.py', so i remove in requirements.txt
run setup.sh , get the error
Collecting cloudpickle
  Using cached https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
Collecting joblib>=0.11
  Using cached https://files.pythonhosted.org/packages/8f/42/155696f85f344c066e17af287359c9786b436b1bf86029bb3411283274f3/joblib-0.14.0-py2.py3-none-any.whl
ERROR: hyperopt 0.2.1 has requirement networkx==2.2, but you'll have networkx 1.11 which is incompatible.
Installing collected packages: numpy, six, absl-py, astor, werkzeug, protobuf, markdown, grpcio, tensorboard, keras-preprocessing, termcolor, h5py, keras-applications, mock, tensorflow-estimator, gast, tensorflow, scipy, sonopy, pyyaml, keras, wavio, typing, prettyparse, attrs, fitipy, joblib, scikit-learn, scikit-optimize, decorator, networkx, portalocker, pyparsing, python-dateutil, cycler, kiwisolver, matplotlib, bson, tqdm, future, cloudpickle, hyperopt, bbopt, speechpy-fast, pyache, mycroft-precise

I don't know why it still installed hyperopt , but failed
when I run precise-train, throw exception
Traceback (most recent call last):
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.11 (/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages), Requirement.parse('networkx==2.2'), {'hyperopt'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gary/mycroft-precise/.venv/bin/precise-train", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.11 (/home/gary/mycroft-precise/.venv/lib/python3.5/site-packages), Requirement.parse('networkx==2.2'), {'hyperopt'})

**Comment by garymmi** [comment]
I solved the problem
finally , I add  to install_requires in setup.py
        'networkx==1.11',
        'hyperopt==0.1.2'

**Comment by gcoon151** [comment]
https://github.com/MycroftAI/mycroft-precise/pull/93
